language: python

python:
  - "2.7"
  - "3.4"

install:
  - python setup.py install

script:
  - nosetests --with-coverage --cover-package=yapf
  - yapf --diff --style=yapf -r yapf yapftests setup.py | test -n -

after_success:
  - pip install --quiet coveralls
  - coveralls
